import React from 'react';
import { Composition, Series, AbsoluteFill, useCurrentFrame, Sequence, Audio, staticFile } from 'remotion';
import { FPS } from './config/constants';
import { Background } from './components/Background';
import { Character } from './components/Character';
import { Subtitle } from './components/Subtitle';
import type { ScriptData, DialogueLine } from './types';

// Dynamic script data generated by the python pipeline
// Pipeline writes to src/script.json before Remotion renders
import rawData from './script.json';

const fallbackData: ScriptData = {
	scenes: [],
	totalDuration: 100,
	fps: FPS,
};

const scriptData: ScriptData = (rawData as ScriptData) ?? fallbackData;

export const RemotionRoot: React.FC = () => {
	return (
		<Composition
			id="DynamicVideo"
			component={DynamicMovie}
			durationInFrames={scriptData.totalDuration}
			fps={FPS}
			width={1920}
			height={1080}
		/>
	);
};

const DynamicMovie: React.FC = () => {
	return (
		<Series>
			{scriptData.scenes.map((scene) => (
				<Series.Sequence
					key={scene.id}
					durationInFrames={scene.durationInFrames}
				>
					<DynamicScene scene={scene} />
				</Series.Sequence>
			))}
		</Series>
	);
};

const DynamicScene: React.FC<{ scene: ScriptData['scenes'][0] }> = ({ scene }) => {
	const frame = useCurrentFrame();

	// Identify all unique speakers in this scene
	const speakersInScene = Array.from(
		new Set(scene.dialogue.map((d) => d.speaker))
	);

	// Find the active dialogue line at the current frame (scene-relative frame + scene.startFrame = global frame)
	const activeLine: DialogueLine | undefined = scene.dialogue.find((d) => {
		const globalFrame = frame + scene.startFrame;
		return globalFrame >= d.startFrame && globalFrame < d.startFrame + d.durationInFrames;
	});

	return (
		<AbsoluteFill>
			{/* Background */}
			<Background type={scene.background} frame={frame} />

			{/* Characters */}
			{speakersInScene.map((speaker, index) => {
				const isActive = activeLine?.speaker === speaker;
				const expression = isActive && activeLine ? activeLine.expression : 'normal';

				// Position characters evenly across the screen
				const numSpeakers = speakersInScene.length;
				let leftPercent = 50;
				if (numSpeakers > 1) {
					leftPercent = 20 + (60 / (numSpeakers - 1)) * index;
				}

				return (
					<Character
						key={speaker}
						type={speaker}
						expression={expression}
						isSpeaking={isActive}
						sceneFrame={frame}
						speakingStartFrame={isActive && activeLine ? activeLine.startFrame - scene.startFrame : 0}
						style={{
							bottom: 140,
							left: `${leftPercent}%`,
							zIndex: isActive ? 10 : 1,
						}}
					/>
				);
			})}

			{/* Audio tracks — render at scene level for reliable playback */}
			{scene.dialogue.map((line, idx) => {
				const startFrameInScene = line.startFrame - scene.startFrame;
				return (
					<Sequence
						key={`audio-${idx}`}
						from={startFrameInScene}
						durationInFrames={line.durationInFrames}
					>
						<Audio src={staticFile(`audio/${line.audio}`)} />
					</Sequence>
				);
			})}

			{/* Dialogue subtitles */}
			{scene.dialogue.map((line, idx) => {
				const startFrameInScene = line.startFrame - scene.startFrame;
				return (
					<Sequence
						key={`sub-${idx}`}
						from={startFrameInScene}
						durationInFrames={line.durationInFrames}
					>
						<Subtitle
							speaker={line.speaker}
							text={line.text}
							expression={line.expression}
						/>
					</Sequence>
				);
			})}
		</AbsoluteFill>
	);
};
