import React, { useMemo } from 'react';
import {
	Composition,
	AbsoluteFill,
	useCurrentFrame,
	Sequence,
	Audio,
	staticFile,
	interpolate,
	spring,
	useVideoConfig,
} from 'remotion';
import { TransitionSeries, linearTiming, linearBlur } from '@remotion/transitions';
import { FPS } from './config/constants';
import { Background } from './components/Background';
import { Character } from './components/Character';
import { Subtitle } from './components/Subtitle';
import { NoiseOverlay } from './components/NoiseOverlay';
import type { ScriptData, DialogueLine, Expression } from './types';

// Dynamic script data generated by the python pipeline
// Pipeline writes to src/script.json before Remotion renders
import rawData from './script.json';

const fallbackData: ScriptData = {
	scenes: [],
	totalDuration: 100,
	fps: FPS,
};

const scriptData: ScriptData = (rawData as ScriptData) ?? fallbackData;

// ── Transition config ────────────────────────────────────────────────────
const TRANSITION_DURATION = 10; // ~0.4s at 24fps — tighter than before

// Transitions add extra frames between scenes
const totalWithTransitions =
	scriptData.totalDuration +
	(scriptData.scenes.length - 1) * TRANSITION_DURATION;

// ── Composition ──────────────────────────────────────────────────────────

export const RemotionRoot: React.FC = () => {
	return (
		<Composition
			id="DynamicVideo"
			component={DynamicMovie}
			durationInFrames={Math.max(1, totalWithTransitions)}
			fps={FPS}
			width={1920}
			height={1080}
		/>
	);
};

// ── DynamicMovie: Scenes with smooth transitions ─────────────────────────

const DynamicMovie: React.FC = () => {
	return (
		<TransitionSeries>
			{scriptData.scenes.flatMap((scene, index) => {
				const elements: React.ReactNode[] = [
					<TransitionSeries.Sequence
						key={scene.id}
						durationInFrames={scene.durationInFrames}
					>
						<DynamicScene scene={scene} sceneIndex={index} />
					</TransitionSeries.Sequence>,
				];
				if (index < scriptData.scenes.length - 1) {
					elements.push(
						<TransitionSeries.Transition
							key={`t-${index}`}
							presentation={linearBlur({})}
							timing={linearTiming({
								durationInFrames: TRANSITION_DURATION,
							})}
						/>,
					);
				}
				return elements;
			})}
		</TransitionSeries>
	);
};

// ── Mood-based lighting overlay config ─────────────────────────────────────
interface MoodLighting {
	label: string;
	tint: string;
	tintOpacity: number;
	vignette: number;
	brightness: number;
	contrast: number;
	warmth: number;
}

const MOOD_LIGHTING: Record<string, MoodLighting> = {
	normal: {
		label: 'Neutral',
		tint: 'transparent',
		tintOpacity: 0,
		vignette: 0.3,
		brightness: 1,
		contrast: 1,
		warmth: 0,
	},
	happy: {
		label: 'Warm & Bright',
		tint: '#FFE082',
		tintOpacity: 0.08,
		vignette: 0.15,
		brightness: 1.08,
		contrast: 1.05,
		warmth: 1,
	},
	angry: {
		label: 'Intense',
		tint: '#FF5252',
		tintOpacity: 0.1,
		vignette: 0.5,
		brightness: 0.92,
		contrast: 1.15,
		warmth: 1,
	},
	shocked: {
		label: 'Bright Flash',
		tint: '#E3F2FD',
		tintOpacity: 0.15,
		vignette: 0.35,
		brightness: 1.12,
		contrast: 1.1,
		warmth: -1,
	},
	thinking: {
		label: 'Dreamy / Soft',
		tint: '#E8EAF6',
		tintOpacity: 0.08,
		vignette: 0.4,
		brightness: 0.95,
		contrast: 0.9,
		warmth: -0.5,
	},
	listening: {
		label: 'Neutral / Soft',
		tint: 'transparent',
		tintOpacity: 0.04,
		vignette: 0.25,
		brightness: 1,
		contrast: 1,
		warmth: 0,
	},
};

/**
 * Mood-based lighting overlay — CSS filter + tint/vignette overlay
 * that responds to the active dialogue expression.
 */
const LightingOverlay: React.FC<{
	expression: Expression;
	sceneFrame: number;
}> = ({ expression, sceneFrame }) => {
	const mood: MoodLighting =
		(MOOD_LIGHTING[expression] ?? MOOD_LIGHTING.normal) as MoodLighting;

	const transitionSpeed = 0.04;
	const transition = Math.min(1, sceneFrame * transitionSpeed);

	const pulseAmount =
		expression === 'shocked'
			? Math.sin(sceneFrame * 0.3) * 0.04
			: expression === 'happy'
				? Math.sin(sceneFrame * 0.15) * 0.02
				: 0;

	const brightness = mood.brightness + pulseAmount;
	const targetSat = mood.warmth > 0 ? 1.08 : mood.warmth < 0 ? 0.95 : 1;

	return (
		<AbsoluteFill
			style={{
				zIndex: 50,
				pointerEvents: 'none',
				filter: `
					brightness(${(brightness * transition + 1 * (1 - transition)).toFixed(3)})
					contrast(${(mood.contrast * transition + 1 * (1 - transition)).toFixed(3)})
					saturate(${(targetSat * transition + 1 * (1 - transition)).toFixed(3)})
				`,
				opacity: transition,
			}}
		>
			{mood.tint !== 'transparent' && (
				<div
					style={{
						position: 'absolute',
						top: 0,
						left: 0,
						width: '100%',
						height: '100%',
						backgroundColor: mood.tint,
						opacity: mood.tintOpacity * transition,
					}}
				/>
			)}
			<div
				style={{
					position: 'absolute',
					top: 0,
					left: 0,
					width: '100%',
					height: '100%',
					background: `radial-gradient(
						ellipse at center,
						transparent 40%,
						rgba(0,0,0,${(mood.vignette * transition * 0.8).toFixed(3)}) 100%
					)`,
				}}
			/>
		</AbsoluteFill>
	);
};

// ── Camera constants ─────────────────────────────────────────────────────
const CAMERA_ZOOM_INTENSITY = 0.04;
const CAMERA_PAN_INTENSITY = 40;
const CAMERA_PUSH_INTENSITY = 0.03;

// ── DynamicScene: Per-scene content with camera movement ─────────────────

const DynamicScene: React.FC<{
	scene: ScriptData['scenes'][0];
	sceneIndex: number;
}> = ({ scene, sceneIndex }) => {
	const frame = useCurrentFrame();
	const { fps } = useVideoConfig();

	// ── Precompute speakers list (stable per scene) ──────────────────────
	const speakersInScene = useMemo(
		() => Array.from(new Set(scene.dialogue.map((d) => d.speaker))),
		[scene.dialogue],
	);

	// ── Find active dialogue line ───────────────────────────────────────
	const activeLine: DialogueLine | undefined = useMemo(() => {
		return scene.dialogue.find((d) => {
			const globalFrame = frame + scene.startFrame;
			return (
				globalFrame >= d.startFrame &&
				globalFrame < d.startFrame + d.durationInFrames
			);
		});
	}, [frame, scene.dialogue, scene.startFrame]);

	const activeSpeaker = activeLine?.speaker ?? null;
	const listeningSpeaker = activeSpeaker
		? speakersInScene.find((s) => s !== activeSpeaker) ?? null
		: null;

	// ── Camera position ─────────────────────────────────────────────────
	const activeSpeakerIndex = activeLine
		? speakersInScene.indexOf(activeLine.speaker)
		: -1;

	let targetPan = 0;
	if (activeSpeakerIndex >= 0 && speakersInScene.length > 1) {
		targetPan = interpolate(
			activeSpeakerIndex,
			[0, speakersInScene.length - 1],
			[-CAMERA_PAN_INTENSITY, CAMERA_PAN_INTENSITY],
		);
	}

	const cameraPanSpring = spring({
		frame,
		fps,
		config: { damping: 15, stiffness: 8, mass: 0.8 },
	});

	const expressiveness =
		activeLine?.expression === 'shocked'
			? 1
			: activeLine?.expression === 'angry'
				? 0.8
				: activeLine?.expression === 'happy'
					? 0.6
					: 0;
	const pushIn = expressiveness * CAMERA_PUSH_INTENSITY;
	const cameraZoom = 1 + (activeLine ? CAMERA_ZOOM_INTENSITY : 0) + pushIn;

	const cameraTransform = `
		translateX(${(targetPan * cameraPanSpring).toFixed(1)}px)
		scale(${cameraZoom.toFixed(4)})
	`;

	return (
		<AbsoluteFill>
			{/* Camera movement container */}
			<AbsoluteFill
				style={{
					transform: cameraTransform,
					transformOrigin: 'center center',
				}}
			>
				{/* Background */}
				<Background type={scene.background} frame={frame} />

				{/* Characters */}
				{speakersInScene.map((speaker, index) => {
					const isActive = activeLine?.speaker === speaker;
					const isListening = !isActive && listeningSpeaker === speaker;
					const expression =
						isActive && activeLine
							? activeLine.expression
							: 'normal';

					const numSpeakers = speakersInScene.length;
					let leftPercent = 50;
					if (numSpeakers > 1) {
						leftPercent = 20 + (60 / (numSpeakers - 1)) * index;
					}

					return (
						<Character
							key={speaker}
							type={speaker}
							expression={expression}
							{...(isListening ? { listeningExpression: 'listening' as const } : {})}
							isSpeaking={isActive}
							sceneFrame={frame}
							speakingStartFrame={
								isActive && activeLine
									? activeLine.startFrame - scene.startFrame
									: 0
							}
							style={{
								bottom: 140,
								left: `${leftPercent}%`,
								zIndex: isActive ? 10 : 1,
							}}
						/>
					);
				})}
			</AbsoluteFill>

			{/* Mood-based lighting overlay */}
			<LightingOverlay
				expression={activeLine?.expression ?? 'normal'}
				sceneFrame={frame}
			/>

			{/* Subtle film grain / noise texture */}
			<NoiseOverlay opacity={0.015} intensity={0.4} />

			{/* Audio tracks */}
			{scene.dialogue.map((line, idx) => {
				const startFrameInScene = line.startFrame - scene.startFrame;
				return (
					<Sequence
						key={`audio-${idx}`}
						from={startFrameInScene}
						durationInFrames={line.durationInFrames}
					>
						<Audio src={staticFile(`audio/${line.audio}`)} />
					</Sequence>
				);
			})}

			{/* Dialogue subtitles */}
			{scene.dialogue.map((line, idx) => {
				const startFrameInScene = line.startFrame - scene.startFrame;
				return (
					<Sequence
						key={`sub-${idx}`}
						from={startFrameInScene}
						durationInFrames={line.durationInFrames}
					>
						<Subtitle
							speaker={line.speaker}
							text={line.text}
							expression={line.expression}
						/>
					</Sequence>
				);
			})}
		</AbsoluteFill>
	);
};
